name: Deploy portafolio react + vite to GitHub Pages

on:
  push:
    branches:
      - main # Set the branch you want to deploy from

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      #Extraer, consultar el codigo fuente
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Specify the Node.js version you want to use

      #Instalar dependencias
      - name: Install dependencies
        run: npm install

      #Construir el proyecto
      - name: Build the project
        run: npm run build

      # Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Set the branch to deploy to (default is 'gh-pages')
          # target_branch: gh-pages
